### ISSUE TITLE
Unable to restart the beacon chain after updating

### ISSUE THREAD

**Issue by suzukirexcess** [dappnode/DAppNodePackage-teku#19]
After updating Teku to 2.0.0 using the MyDappnode UI the beacon chain will not restart. Left it running for about 10 minutes but the indicator still just said "restarting", then:
- Attempted a restart of just the beacon chain service on the Packages > Teku page but it didn't relaunch.
- Attempted a restart of the entire MyDappnode, after Teku restarted the beacon chain still shows as "restarting"

<img width="1205" alt="Screen Shot 2022-09-26 at 5 03 37 PM" src="https://user-images.githubusercontent.com/13156309/192381095-50ce0895-4942-4c1b-804d-0bfef472f194.png">

**Comment by alexpeterson91** [comment]
duplicate issue, will be resolved via Discord support
