### ISSUE TITLE
Unable to update from 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by suzukirexcess** [dappnode/DAppNodePackage-teku#20]
After updating to Teku 2.0.0, cannot update the package to 2.0.1 from the MyDappnode UI.

Choosing the Update button on the main Dashboard takes one to the main Teku DAppStore page, but there is no option to Update.
Choosing the Update button on the Packages > Teku page takes one to the main Teku DAppStore page, but there is no option to Update.

<img width="470" alt="Screen Shot 2022-09-26 at 5 02 54 PM" src="https://user-images.githubusercontent.com/13156309/192381861-4aa4ebd7-43b4-49db-a2c6-ea0b46ea54f1.png">
<img width="1212" alt="Screen Shot 2022-09-26 at 5 03 20 PM" src="https://user-images.githubusercontent.com/13156309/192381906-cd5f5960-2816-4b96-9345-60e033b32219.png">
<img width="1210" alt="Screen Shot 2022-09-26 at 5 03 07 PM" src="https://user-images.githubusercontent.com/13156309/192381932-b6c35364-5ae9-4b4d-a4d3-92a8b6ba3241.png">

**Comment by alexpeterson91** [comment]
If you're still having this issue you will find support on our [Discord Server](https://discord.gg/dappnode)
