### ISSUE TITLE
Updating from 2.0.1 (22.9.1 upstream) to 2.0.2 (22.10.1 upstream) fails

### ISSUE THREAD

**Issue by alundkvist** [dappnode/DAppNodePackage-teku#28]
Updating gives this error message:

Reply: Command failed: docker-compose -f /usr/src/app/dnp_repo/teku.dnp.dappnode.eth/docker-compose.yml up --detach <&- Container DAppNodePackage-validator.teku.dnp.dappnode.eth Starting Container DAppNodePackage-beacon-chain.teku.dnp.dappnode.eth Starting Container DAppNodePackage-beacon-chain.teku.dnp.dappnode.eth Started Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "entrypoint.sh": executable file not found in $PATH: unknown

**Comment by alexpeterson91** [comment]
Please go to discord for technical support, but this issue has already been resolved so I'm going to close this.  Sorry for the inconvenience.
